// - LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN = "LOGIN";
export const LOGIN_START = "LOGIN_START";
export const CHANGE_USERSESSION = "CHANGE_USERSESSION";
export const CHANGE_LOGIN = "CHANGE_LOGIN";
export const CHANGE_LOGINSTATUS = "CHANGE_LOGINSTATUS"



//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_CONFIG = 'CHANGE_CONFIG';
export const CHANGE_CONFIG_API = 'CHANGE_CONFIG_API';
