require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.0'

target 'masterdiskon' do
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  
  # pod 'RNSVG', :path => '../node_modules/react-native-svg'

  # target 'masterdiskonTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

# target 'masterdiskon-tvOS' do
#   # Pods for [YourProjectName]-tvOS

#   target 'masterdiskon-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end